# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesabe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Credential',
        ),
    ]
