# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabe_app', '0002_auto_20200126_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='merchant_code',
            field=models.IntegerField(),
        ),
    ]
